name: PR Checks
on:
  pull_request:
  workflow_dispatch:

jobs:
  repo-checks:
    name: Install and Cache
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Cancel Previous Workflows In Progress
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Run Format, Test, and Build
        run: pnpm build