name: PR Checks
on:
  pull_request:
  workflow_dispatch:

jobs:
  repo-checks:
    name: Install and Cache

    steps:
      - name: Cancel Previous Workflows In Progress
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20

      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-nodemodules
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Format, Test, and Build
        run: yarn build